config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'visitors#index'

  resources :patient_profiles, only: [:index, :show, :edit, :update, :create]
  resources :exercise_patient, only: [:new, :edit, :delete]
  resource :therapist_profile, only: [:show, :edit, :update, :create]
  resources :exercises
  resource  :motivational_message, only: [:show]

  get '/about' => 'visitors#about'
  get '/contact' => 'visitors#contact'

  post '/therapist_profile/corelate_excercises' => "therapist_profiles#corelate_exercises"
  post '/therapist_profile/add_exercise' => "therapist_profiles#add_exercise"

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  	
  	expose(:exercise)
    expose(:exercises)
    
    def index
    end

    def new      
  	end

  	def edit
  	end


  	def create
  	  self.exercise = Exercise.new(exercise_params)

      if exercise.save
        redirect_to exercises_url, notice: 'Exercise was successfully created.'
      else
        render action: 'new'
      end
    end

    def update
      if exercise.update(exercise_params)
        redirect_to exercise, notice: 'Exercise was successfully updated.'
      else
        render action: 'edit'
      end
    end

    def destroy
      exercise.destroy
      redirect_to exercises_url, notice: 'Exercise was successfully destroyed.'
    end

	private
      def exercise_params
        params.require(:exercise).permit(:name, :description)
      end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.haml
= render 'layouts/messages'

.row
  .col-md-4
    = form_for exercise do |f|   
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_field :description, class: 'form-control'
      = f.submit 'Save', class: 'btn btn-default'

app/views/exercises/edit.html.haml
%h1 Editing exercise

= render 'form'

app/views/exercises/index.html.haml
%h1.exercisehead
  All exercises

%p
=link_to 'Add a New Exercise', new_exercise_path, class: "btn  btn-default "

%table.table.table-hover
  %thead
    %tr
      %td
        %strong Name
      %td
        %strong Description
      %td
      %td
  - exercises.each do |exercise|
    %tr
      .exercise
        %td
          = exercise.name
        %td
          =exercise.description
        %td
          = link_to 'Edit', edit_exercise_path(exercise), class: "btn btn-warning"
        %td
          = link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger"

app/views/exercises/new.html.haml
%h1.exercise
  New exercise

= render 'form'

app/views/exercises/show.html.haml
%h1.exercise
  Exercises
  
  =exercise.name
  
- if exercises.empty?
  No exercises
  