config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'visitors#index'

  resources :patient_profiles, only: [:index, :show, :edit, :update, :create]
  resources :exercise_patient, only: [:new, :edit, :delete]
  resource :therapist_profile, only: [:show, :edit, :update, :create]
  resources :exercises
  resource  :motivational_message, only: [:show]

  get '/about' => 'visitors#about'
  get '/contact' => 'visitors#contact'

  post '/therapist_profile/corelate_excercises' => "therapist_profiles#corelate_exercises"
  post '/therapist_profile/add_exercise' => "therapist_profiles#add_exercise"

end

app/views/layouts/_footer.html.haml
2015 Phizzy™ © ®

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Home', root_path
- if !signed_in?
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- else
  %li= link_to 'Profile', (current_user.profilable.kind_of?(PatientProfile) ? patient_profiles_path : therapist_profile_path)
  -if current_user.profilable.kind_of?(TherapistProfile)
    %li= link_to 'Exercises', exercises_path
  %li= link_to 'Sign out', destroy_user_session_path, method: :delete
%li= link_to 'About', about_path
%li= link_to 'Contact', contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Phizzy'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Phizzy'}"}
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .masthead
        %h3.text-muted
          Phizzy!
          - if signed_in?
            %small Logged in as #{current_user.decorate.full_name}
        %nav
          %ul.nav.nav-justified
            = render 'layouts/navigation_links'
      .masthead
        =render 'layouts/messages'
      =yield

    -#%header
      = render 'layouts/navigation'
    -#%main{:role => "main"}
      = render 'layouts/messages'
      = yield
    %footer{:class => "footer"}
      = render 'layouts/footer'

:javascript 
  $('.alert').fadeOut(4000);